// ============================================================================
// Tool: execute_sql_ai — AI-generated SQL with mandatory placeholders
// ============================================================================
//
// This tool executes SQL generated by the AI. It enforces parameterised
// placeholders (?) to prevent SQL injection. Every literal value must use
// a ? placeholder with a corresponding entry in the parameters array.
//
// ============================================================================

import { z } from 'zod';
import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { validateAnySql } from '../guardrails/index.js';
import { validateInput } from '../sanitisation/inputValidator.js';
import { sanitiseUpdate } from '../sanitisation/updateSanitiser.js';
import { validatePlaceholders } from '../guardrails/placeholderValidator.js';
import { DbAdapter } from '../db/adapter.js';
import { AuditLogger } from '../logging/auditLogger.js';
import { Config } from '../config/settings.js';
import { OperationType } from '../types/index.js';
import { RateLimiter } from '../rateLimit/rateLimiter.js';

/** Check if SQL is an anonymous block (DO BEGIN...END or BEGIN...END). */
function isAnonymousBlock(sql: string): boolean {
  const upper = sql.trim().toUpperCase();
  return upper.startsWith('DO') || upper.startsWith('BEGIN');
}

export function registerSqlAiTool(
  server: McpServer, adapter: DbAdapter, logger: AuditLogger, config: Config, rateLimiter: RateLimiter,
): void {
  // Dynamic getters — values change when the active database connection switches
  const dbName = () => adapter.getDbName() || '(not connected)';
  const dbType = () => adapter.getDbType();

  server.tool(
    'execute_sql_ai',
    `Execute an AI-generated SQL statement against the currently connected database.

IMPORTANT: Use this tool for ALL AI-generated SQL queries. Do NOT use this for user-provided queries — use "execute_sql" instead.

IMPORTANT: Before calling this tool, you MUST confirm which database the user intends to query. If the user has not explicitly stated the target database in their message, ASK them first. Do NOT assume the currently connected database is the intended target.

Parameterized placeholders (?) are MANDATORY. Every literal value in WHERE, SET, VALUES, or HAVING clauses must use ? with a corresponding entry in the parameters array. The server will reject queries where the placeholder count does not match the parameters count.

Supports: SELECT, UPDATE, INSERT, DELETE, and DO BEGIN...END blocks.

Example SELECT:
  query: SELECT "ItemCode", "ItemName" FROM OITM WHERE "ItmsGrpCod" = ? AND "ItemName" LIKE ?
  parameters: [100, "%filter%"]

Example UPDATE:
  query: UPDATE ORDR SET "U_CustomField" = ? WHERE "DocEntry" = ?
  parameters: ["new value", 152]

Example INSERT:
  query: INSERT INTO "@MY_UDT" ("Code", "Name", "U_Value") VALUES (?, ?, ?)
  parameters: ["001", "Test", 42]

Rules enforced server-side:
- Placeholder count must match parameters count.
- SAP core tables (4-char names): UPDATE only on U_* fields. INSERT and DELETE are blocked.
- SAP user tables (@-prefixed): INSERT and DELETE require user confirmation.
- Direct EXEC/EXECUTE/CALL: blocked — use "execute_procedure" tool instead.
- CREATE/ALTER: blocked.`,
    {
      query: z.string().describe('The SQL query with ? placeholders for all literal values'),
      parameters: z.array(z.union([z.string(), z.number(), z.boolean(), z.null()]))
        .describe('Parameter values matching each ? placeholder in order'),
      confirmed: z.boolean().optional().describe('Set to true after the user has confirmed a risky operation (e.g., DELETE on SAP user tables)'),
    },
    async ({ query, parameters, confirmed }) => {
      const rateCheck = rateLimiter.check('execute_sql_ai');
      if (!rateCheck.allowed) {
        return { content: [{ type: 'text' as const, text: `Rate limit exceeded for execute_sql_ai. Try again in ${Math.ceil(rateCheck.retryAfterMs / 1000)}s.` }], isError: true };
      }

      const params = parameters || [];

      // Input validation (null bytes, length, etc.)
      const inputCheck = validateInput(query);
      if (!inputCheck.safe) {
        logger.log(logger.createEntry({ tool: 'execute_sql_ai', database: dbName(), dbType: dbType(), operation: OperationType.OTHER, tables: [], query, decision: 'DENY', reason: inputCheck.reason!, rule: 'inputValidation' }));
        return { content: [{ type: 'text' as const, text: `Query rejected: ${inputCheck.reason}` }], isError: true };
      }

      // Mandatory placeholder validation
      const placeholderCheck = validatePlaceholders(query, params);
      if (!placeholderCheck.valid) {
        logger.log(logger.createEntry({ tool: 'execute_sql_ai', database: dbName(), dbType: dbType(), operation: OperationType.OTHER, tables: [], query, decision: 'DENY', reason: placeholderCheck.reason!, rule: 'placeholderValidation' }));
        return { content: [{ type: 'text' as const, text: `Query rejected: ${placeholderCheck.reason}` }], isError: true };
      }

      // For anonymous blocks: validate placeholders and execute
      if (isAnonymousBlock(query)) {
        const auditEntry = logger.createEntry({
          tool: 'execute_sql_ai', database: dbName(), dbType: dbType(),
          operation: OperationType.OTHER, tables: [],
          query, decision: 'ALLOW',
          reason: 'Anonymous block — placeholders validated.',
          rule: 'anonymousBlock',
        });
        logger.log(auditEntry);

        if (config.dryRun) {
          return { content: [{ type: 'text' as const, text: `[DB: ${dbName()}] [DRY RUN] Anonymous block validated and ALLOWED.\nPlaceholders: ${params.length}\nSQL: ${query}` }] };
        }

        try {
          const result = await adapter.executeSql(query, params);
          auditEntry.durationMs = result.durationMs;
          const output = result.data != null
            ? `[DB: ${dbName()}] ${result.rowCount} row(s) returned/affected.\n${JSON.stringify(result.data, null, 2)}`
            : `[DB: ${dbName()}] Executed successfully. ${result.rowCount} row(s) affected.`;
          return { content: [{ type: 'text' as const, text: output }] };
        } catch (err) {
          const errorMsg = err instanceof Error ? err.message : String(err);
          auditEntry.error = errorMsg;
          logger.log(auditEntry);
          return { content: [{ type: 'text' as const, text: `[DB: ${dbName()}] Execution failed: ${errorMsg}` }], isError: true };
        }
      }

      // --- Simple statement path: full guardrail validation ---
      const guardrail = validateAnySql(query);

      if (!guardrail.allowed) {
        logger.log(logger.createEntry({ tool: 'execute_sql_ai', database: dbName(), dbType: dbType(), operation: guardrail.parsed.operation, tables: guardrail.parsed.tables, query, decision: 'DENY', reason: guardrail.reason, rule: guardrail.rule }));
        return { content: [{ type: 'text' as const, text: `[DB: ${dbName()}] ${guardrail.reason}` }], isError: true };
      }

      // Confirmation gate
      if (guardrail.requiresConfirmation && !confirmed) {
        logger.log(logger.createEntry({ tool: 'execute_sql_ai', database: dbName(), dbType: dbType(), operation: guardrail.parsed.operation, tables: guardrail.parsed.tables, query, decision: 'PENDING_CONFIRMATION', reason: guardrail.reason, rule: guardrail.rule }));
        return { content: [{ type: 'text' as const, text: `[DB: ${dbName()}] ${guardrail.confirmationMessage!}\n\nTo proceed, call this tool again with the same parameters and \`confirmed: true\`.` }] };
      }

      // Additional sanitisation for UPDATE statements (4-layer defence)
      if (guardrail.parsed.operation === OperationType.UPDATE) {
        const sanitisation = sanitiseUpdate(query);
        if (!sanitisation.safe) {
          logger.log(logger.createEntry({ tool: 'execute_sql_ai', database: dbName(), dbType: dbType(), operation: OperationType.UPDATE, tables: guardrail.parsed.tables, query, decision: 'DENY', reason: sanitisation.reason!, rule: 'updateSanitiser' }));
          return { content: [{ type: 'text' as const, text: `[DB: ${dbName()}] Update sanitisation failed: ${sanitisation.reason}` }], isError: true };
        }
      }

      // Audit and execute
      const auditEntry = logger.createEntry({
        tool: 'execute_sql_ai', database: dbName(), dbType: dbType(),
        operation: guardrail.parsed.operation,
        tables: guardrail.parsed.tables,
        query, decision: 'ALLOW',
        reason: guardrail.reason, rule: guardrail.rule,
      });
      logger.log(auditEntry);

      if (config.dryRun) {
        return { content: [{ type: 'text' as const, text: `[DB: ${dbName()}] [DRY RUN] Query validated and ALLOWED.\nOperation: ${guardrail.parsed.operation}\nTables: ${guardrail.parsed.tables.join(', ') || '(none detected)'}\nPlaceholders: ${params.length}\nSQL: ${query}` }] };
      }

      try {
        const result = await adapter.executeSql(query, params);
        auditEntry.durationMs = result.durationMs;

        if (guardrail.parsed.operation === OperationType.SELECT) {
          return { content: [{ type: 'text' as const, text: `[DB: ${dbName()}] ${result.rowCount} row(s) returned.\n${JSON.stringify(result.data, null, 2)}` }] };
        }
        return { content: [{ type: 'text' as const, text: `[DB: ${dbName()}] Executed successfully. ${result.rowCount} row(s) affected.` }] };
      } catch (err) {
        const errorMsg = err instanceof Error ? err.message : String(err);
        auditEntry.error = errorMsg;
        logger.log(auditEntry);
        return { content: [{ type: 'text' as const, text: `[DB: ${dbName()}] Execution failed: ${errorMsg}` }], isError: true };
      }
    },
  );
}
