// ============================================================================
// Tool: execute_sql - User-provided SQL (any operation), fixed DB connection
// ============================================================================
//
// This tool executes raw SQL provided DIRECTLY by the user.
//
// ============================================================================

import { z } from 'zod';
import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { validateAnySql } from '../guardrails/index.js';
import { validateInput } from '../sanitisation/inputValidator.js';
import { formatResult } from './formatResult.js';
import { DbAdapter } from '../db/adapter.js';
import { AuditLogger } from '../logging/auditLogger.js';
import { Config } from '../config/settings.js';
import { OperationType } from '../types/index.js';
import { RateLimiter } from '../rateLimit/rateLimiter.js';
import { OperationCoordinator } from '../security/operationCoordinator.js';

export function registerSqlTool(
  server: McpServer, adapter: DbAdapter, logger: AuditLogger, config: Config,
  rateLimiter: RateLimiter, coordinator: OperationCoordinator,
): void {
  // Dynamic getters - values change when the active database connection switches
  const dbName = () => adapter.getDbName() || '(not connected)';
  const dbType = () => adapter.getDbType();

  server.tool(
    'execute_sql',
    `Execute a raw SQL statement against the currently connected database. All SQL, whether written by the user or generated by you, goes through the same server-side validation.

IMPORTANT: Before calling this tool, you MUST confirm which database the user intends to query. If the user has not explicitly stated the target database in their message, ASK them first. Do NOT assume the currently connected database is the intended target.

READ-ONLY: only SELECT (and read-only DO BEGIN...END blocks) execute. Data-changing statements are blocked server-side.

If the user needs a write (INSERT/UPDATE/DELETE), do NOT call this tool — generate the SQL and give it to the user to run in a real DB client (HANA Studio / DBeaver / hdbsql), where COMMIT is guaranteed.

Rules enforced server-side:
- READ-ONLY: INSERT/UPDATE/DELETE/DROP are blocked for everyone — no confirmation bypass.
- Direct EXEC/EXECUTE/CALL: blocked (stored procedures are disabled).
- CREATE/ALTER: blocked.
- MS SQL pass-through (OPENQUERY/OPENROWSET/OPENDATASOURCE): blocked.`,
    {
      query: z.string().describe('The SQL statement to execute (SELECT only — read-only server)'),
    },
    async ({ query }) => {
      const rateCheck = rateLimiter.check('execute_sql');
      if (!rateCheck.allowed) {
        return { content: [{ type: 'text' as const, text: `Rate limit exceeded for execute_sql. Try again in ${Math.ceil(rateCheck.retryAfterMs / 1000)}s.` }], isError: true };
      }

      return coordinator.runExclusive(async () => {

      // Input validation (null bytes, length, etc.)
      const inputCheck = validateInput(query, config.maxQueryLength);
      if (!inputCheck.safe) {
        logger.log(logger.createEntry({ tool: 'execute_sql', database: dbName(), dbType: dbType(), operation: OperationType.OTHER, tables: [], query, decision: 'DENY', reason: inputCheck.reason!, rule: 'inputValidation' }));
        return { content: [{ type: 'text' as const, text: `Query rejected: ${inputCheck.reason}` }], isError: true };
      }

      // Full guardrail validation for both simple statements and anonymous blocks.
      const guardrail = validateAnySql(query);

      if (!guardrail.allowed) {
        logger.log(logger.createEntry({ tool: 'execute_sql', database: dbName(), dbType: dbType(), operation: guardrail.parsed.operation, tables: guardrail.parsed.tables, query, decision: 'DENY', reason: guardrail.reason, rule: guardrail.rule }));
        return { content: [{ type: 'text' as const, text: `[DB: ${dbName()}] ${guardrail.reason}` }], isError: true };
      }

      // Audit and execute
      const auditEntry = logger.createEntry({
        tool: 'execute_sql', database: dbName(), dbType: dbType(),
        operation: guardrail.parsed.operation,
        tables: guardrail.parsed.tables,
        query, decision: 'ALLOW',
        reason: guardrail.reason, rule: guardrail.rule,
      });
      logger.log(auditEntry);

      if (config.dryRun) {
        return { content: [{ type: 'text' as const, text: `[DB: ${dbName()}] [DRY RUN] Query validated and ALLOWED.\nOperation: ${guardrail.parsed.operation}\nTables: ${guardrail.parsed.tables.join(', ') || '(none detected)'}\nSQL: ${query}` }] };
      }

      try {
        const result = await adapter.executeSql(query);
        auditEntry.durationMs = result.durationMs;
        return { content: [{ type: 'text' as const, text: `[DB: ${dbName()}] ${result.rowCount} row(s) returned.\n${formatResult(result.data, config)}` }] };
      } catch (err) {
        const errorMsg = err instanceof Error ? err.message : String(err);
        auditEntry.error = errorMsg;
        logger.log(auditEntry);
        return { content: [{ type: 'text' as const, text: `[DB: ${dbName()}] Execution failed: ${errorMsg}` }], isError: true };
      }
      });
    },
  );
}
